const {create,sec,table,link}=require('./helpers.cjs');
module.exports=create('clipping-campaign-pricing-budget-india',{
 title:'Clipping campaign pricing in India: build a defensible budget',
 dek:'A complete cost model for fixed-fee, performance-based and hybrid campaigns, with hypothetical rupee examples, payout caps and reconciliation worksheets.',
 description:'Build an Indian clipping campaign budget with fixed fees, eligible-view payouts, caps, review costs and clearly labelled hypothetical calculations.',
 answer:'A clipping campaign budget should specify the paid unit, eligible outcomes, payout caps, operator charges, production costs and review effort. There is no verified universal Indian clipping rate in this guide. Compare written quotes on the same scope, and use a capped pilot to test the cost of approved output before increasing spend.',
 intent:'Provide a full pricing and reconciliation model, rather than an earnings article or a provider price ranking.',section:'guides',
 sections:[
 sec('Price the obligation before comparing quotes',`The word campaign can refer to editing files, publishing on approved accounts, coordinating participants or paying for eligible views. A quote is meaningful only when these obligations are explicit. List the source volume, final deliverables, aspect ratios, caption languages, approval stages, posting responsibilities and evidence requirements. Separate the number of edits from the number of published placements.

Ask each supplier to price the same brief. A low per-clip figure may exclude source selection, translation or revisions that another quote includes. A performance quote may exclude the fixed cost of running the campaign. Keep assumptions beside each line item so that a later scope change has an identifiable cost rather than becoming a surprise invoice.`,[],{links:[link('creator-clipping-brief-template-india','a complete creator brief')]}),
 sec('Choose between fixed, performance and hybrid compensation',`Fixed compensation pays for a defined deliverable or service. Performance compensation depends on an agreed eligible outcome, often after approval and measurement. A hybrid combines a fixed amount with a bounded variable component. None is automatically cheaper or fairer: the allocation of risk and the quality of the definitions determine how the arrangement behaves.

Fixed fees can make an editing pilot easier to reconcile. Performance compensation can align some incentives but may encourage volume or disputable traffic if the brief rewards the wrong metric. A hybrid needs separate rules for earning the base fee and the bonus. An editor should understand which work remains payable if a post underperforms or an account cannot publish.`,[],{sources:['whop','clipping'],table:table(['Structure','What to define','Main budget uncertainty'],[['Fixed deliverable','Accepted file, included revisions, delivery date','Changes beyond the agreed scope'],['Eligible outcome','Metric, validation, rate, window, caps','Approved performance within the pool'],['Hybrid','Base obligation plus bonus rules','Interaction between acceptance and variable pay']])}),
 sec('Create a cost sheet with seven separate buckets',`Budget preparation, editing, language review, publication, campaign administration, tools and the variable payout pool separately. Some projects will not need every bucket. Record a zero or mark a cost as included rather than leaving it ambiguous. Source preparation may involve rights checks and timestamp selection; administration may involve answering questions and reconciling submission records.

Keep internal labour visible even when it is not invoiced by a supplier. A founder spending several hours reviewing captions contributes project cost and has limited capacity. If a platform or agency charges fees, obtain the actual fee basis, taxes where applicable and the currency used. This worksheet does not calculate Indian tax liability; use the invoicing treatment agreed with the relevant professional.`,[],{table:table(['Cost bucket','Input to request'],[['Source preparation','Hours or agreed fixed scope'],['Editing','Accepted exports and included revisions'],['Language review','Languages, reviewer and revision boundary'],['Publishing','Accounts, placements and scheduling'],['Operations','Moderation, approval and reconciliation'],['Tools and fees','Licences, operator/platform charges and tax treatment'],['Variable pool','Rate, eligible denominator, window and maximum']])}),
 sec('Use a fixed-fee example to expose hidden costs',`Hypothetical demonstration: a pilot includes eight accepted edits at an invented ₹750 each, ₹1,200 for source preparation, ₹1,600 for review and ₹700 for project-specific tools. The planned cost is ₹9,500 before any separately applicable tax or distribution cost. These figures demonstrate the model; they are not market rates, a RiseKlix offer or a client result.

If two extra edits are added at the same illustrative rate, the new editing amount is ₹7,500 and the total becomes ₹11,000 only if the other costs remain unchanged. In practice, the extra edits might also require more review. Record that dependency. Dividing ₹9,500 by eight gives ₹1,187.50 per accepted edit, which is a fuller project cost than quoting the editor’s ₹750 alone.`,[],{table:table(['Demonstration line','Calculation','Amount'],[['Accepted editing','8 × ₹750','₹6,000'],['Source preparation','Invented fixed amount','₹1,200'],['Review','Invented fixed amount','₹1,600'],['Tools','Invented project allocation','₹700'],['Planned subtotal','Sum of the four lines','₹9,500']])}),
 sec('Calculate eligible-view payouts with the actual denominator',`For a rate expressed per thousand eligible views, the basic amount is eligible views divided by 1,000, multiplied by the agreed rate. The brief must explain whether payment uses proportional fractions or complete thousand-view blocks. It must also define eligible geography, time window, permitted accounts, excluded traffic and any minimum threshold. A public lifetime count is not automatically the payable count.

Hypothetical proportional example: 42,500 eligible views at an invented ₹80 per thousand yields ₹3,400 before caps or other stated adjustments. If the contract instead pays only complete blocks, 42 blocks would yield ₹3,360. Neither method is implied by the word CPM. Write the rounding rule into the accepted terms before anybody begins work.`,[],{links:[link('how-do-clipping-campaigns-pay-talent','participant compensation definitions')]}),
 sec('Define caps and budget exhaustion before launch',`A payout pool limits total exposure only if the exhaustion rules are clear. Specify campaign, participant and post caps independently where they apply. Explain how eligible submissions compete for the remaining pool and which timestamp determines priority. Avoid promising an unlimited rate while quietly depending on a finite budget.

Hypothetical case: the pool has ₹2,000 remaining when two otherwise eligible posts would each earn ₹1,500. The team must apply the previously published allocation rule. It cannot reasonably invent a winner after seeing the results. Possible contract designs include reserved allocations or a defined proportional settlement, but these are choices to agree in advance. Record the exhaustion time and notify participants through the campaign’s authoritative channel.`,[],{table:table(['Limit','Clarify before work'],[['Post cap','Maximum per submission and treatment of further views'],['Participant cap','Combined ceiling across that participant’s posts'],['Campaign pool','Total variable amount and allocation rule'],['Deadline','Submission, measurement and payment dates'],['Exhaustion','Who announces closure and how existing work is handled']])}),
 sec('Budget approval work and predictable rework',`Choose an approval process that the reviewer can sustain. An initial sample can expose recurring errors before a whole batch is edited. Decide which revisions are included: caption corrections, pacing changes, source replacement or a completely new concept are different requests. Make the acceptance criteria specific enough that an editor can inspect the export before submitting it.

Keep a rework log with the reason and owner. If the sponsor changes the message after an approved cut, classify it as a scope change rather than an editor error. If the editor repeatedly misses a written requirement, fix the production process. This distinction helps forecast the next batch and prevents a low headline editing price from concealing large review costs.`,[],{links:[link('what-counts-as-an-approved-clip','clip acceptance criteria')]}),
 sec('Compare scenarios without calling them forecasts',`Build conservative, middle and upper illustrative scenarios using inputs you can explain. Vary eligible outcome volume, rejection rate or review effort one at a time where possible. Label every unmeasured assumption. A scenario is a planning calculation, not a prediction of views or a promise to participants.

For a capped performance pool, the maximum variable payout may be known even when views are not. Use that ceiling to test affordability. Separately inspect the low-outcome case: what fixed cost remains if the clips produce no useful traffic? A campaign that is affordable only under its most optimistic scenario needs a smaller scope or a clearer business case. Avoid hiding downside behind a single attractive return figure.`,[],{links:[link('creator-clipping-campaign-roi-calculator-india','the blank-input ROI calculator')]}),
 sec('Separate production efficiency from business value',`Cost per accepted edit measures production efficiency. Cost per eligible thousand views measures a distribution outcome using a defined denominator. Cost per qualified enquiry measures a downstream event. These answer different questions. Report the corresponding costs and counts together so that readers can reproduce the calculation.

A campaign may become cheaper to edit while attracting less useful traffic. It may produce fewer views but better enquiries. Choose the business measure before the test, and retain the operational measures for diagnosing the result. When tracking does not establish causation, use language such as observed enquiries from tagged sessions rather than incremental sales generated. This keeps the budget decision attached to evidence instead of a marketing slogan.`,[],{sources:['gaScope'],links:[link('utm-tracking-clipping-campaigns-india','tagged links and attribution limits')]}),
 sec('Reconcile planned, approved, payable and paid amounts',`Maintain four distinct states. Planned is the maximum or expected commitment. Approved is work that passed review. Payable is the amount earned under the agreed calculation. Paid is money actually settled with a reference and date. An approval message should not be represented as a completed transfer, and a pending transfer should not be used as a testimonial about successful payouts.

At closeout, connect each amount to a submission ID, accepted version, evidence timestamp and rate rule. Record excluded items with the published reason and a review route. Keep personal payment details access-controlled rather than in a public campaign leaderboard. A participant should be able to understand their own calculation without seeing everybody else’s sensitive data.`,[],{table:table(['Record field','Purpose'],[['Submission and version','Identify exactly what was accepted'],['Eligible count and time','Explain the measurement basis'],['Rate and caps','Reproduce the earned amount'],['Adjustments and reason','Explain any agreed deduction or correction'],['Settlement reference and date','Confirm actual payment separately']])}),
 sec('Ask better questions when collecting agency quotes',`Request a scope breakdown, not just a monthly total. Ask what happens when a source is unusable, whether the fee includes captions in each required language and how approval delays affect delivery. Confirm who owns project files, publishing accounts and reporting exports. Ask whether participant payouts are included, passed through at cost or charged separately.

For comparisons, write a single quotation sheet and record exclusions next to the price. A supplier who identifies a genuine constraint may provide a more useful quote than one promising unlimited clips and guaranteed virality. If any commercial term is missing, treat the number as provisional. Do not describe an informal online rate card as an India-wide benchmark.`,[],{links:[link('how-to-choose-clipping-agency-india','an evidence-based agency scorecard')]}),
 sec('Set the next budget from the pilot’s actual bottleneck',`Once the pilot closes, compare planned and actual amounts bucket by bucket. Identify whether spending changed because of more output, avoidable errors, audience testing or a scope change. Update the next estimate using those recorded causes. A single success story is not enough to infer stable costs across different creators or languages.

Decide what the next increment buys. More edits, another language and more distribution accounts require different support. Preserve some capacity for reviewing the new variable rather than spending the entire budget on production. The most defensible clipping campaign price is the amount attached to a clear obligation, a bounded risk and a reconciliation process that both parties can understand.`)
 ],faq:[
 ['What is the average cost of a clipping campaign in India?', 'This guide does not establish an Indian average. Campaigns vary in editing, source preparation, language review, publishing, administration and outcome-based compensation. Obtain current written quotes for a common brief and compare the full project cost. The rupee amounts shown here are invented teaching inputs, not surveyed market prices.'],
 ['Is paying per view cheaper than paying per clip?', 'It depends on the eligible volume, rate, caps, fixed operating costs and the quality of the outcome. A per-view structure transfers some performance risk but creates validation and allocation work. A per-clip structure can make deliverables predictable. Compare both using the same budget ceiling and a clearly defined success measure.'],
 ['What does CPM mean in a clipping campaign?', 'A campaign may use CPM to describe payment per thousand eligible views, but the exact contract definition governs. Confirm which views qualify, whether partial thousands are paid, the measurement date and any caps. An advertising CPM, a public view count and a participant payout rate should not be treated as interchangeable values.'],
 ['Should revisions be included in the editing price?', 'State a reasonable revision scope before accepting the quote. Caption corrections, small timing adjustments and a new concept are different kinds of work. Specify rounds, deadlines and the owner of each change. Record sponsor scope changes separately from corrections to an export that missed the written brief.'],
 ['How do I budget when views are unpredictable?', 'Cap the variable payout obligation, define the allocation rule and include fixed costs even in a zero-outcome scenario. Use labelled scenarios to test affordability. Begin with a reviewable pilot and increase only when the evidence explains what the next spend is expected to test. A scenario does not predict performance.'],
 ['When is a payout considered complete?', 'When the money has actually settled and the relevant payment record confirms it. Approval, payable calculation and a transfer attempt are earlier states. Keep them distinct in participant communications and reporting. Follow the agreed dispute process when an amount or settlement status is contested.']
 ]
});
