const {create,sec,table,link}=require('./helpers.cjs');
module.exports=create('is-video-clipping-legal-in-india',{
 title:'Is video clipping legal in India? Rights, licences and a clearance workflow',
 dek:'Understand the permissions questions behind podcast, streamer and creator clips, then build a source-by-source record before editing or distributing.',
 description:'A practical Indian video clipping rights guide covering written licences, source clearance, music, guest material and copyright claim handling.',
 answer:'Video clipping in India depends on the rights in the material and the authorised use. Written permission from the relevant rights holder is a practical starting point for commercial campaigns. Credit, a short duration or access to a public video does not itself establish permission. Copyright exceptions need case-specific assessment; platform and advertising rules also apply.',
 intent:'Explain rights clearance and operational records for commercial clipping, without issuing a legal opinion about an individual video.',section:'guides',
 sections:[
 sec('Start with the rights in the source',`The Copyright Office’s published Act text identifies protected categories including literary, musical and artistic works, films and sound recordings. Rights depend on the type of work. A video may contain several separately controlled elements, so permission to use the recording does not automatically clear everything visible or audible in it.

For a campaign, create a source inventory before selecting moments. Record who supplied each file, who claims ownership and what supporting agreement exists. Treat uncertainty as a question to resolve, not as proof of infringement or permission. This guide offers an operating workflow, not a determination that a particular upload is lawful. The official chapter pages were available through indexed text during research; direct retrieval was unreliable, and this is not an exhaustive amendment or case-law review.`,[],{sources:['copyrightWorks']}),
 sec('Distinguish access, credit and a licence',`Being able to watch or download a public video is different from being authorised to redistribute edited extracts. A creator tag helps identify the source but does not explain the permitted platforms, accounts, commercial purpose or duration. An informal statement such as share my content can leave important campaign obligations unresolved.

Chapter VI of the published Indian Act provides for licences in writing from the owner or a duly authorised agent. For a commercial campaign, request a record that identifies the material and the planned use. Ask a qualified adviser to review the agreement where rights are complex or contested. Do not assume that the person sending the file can licence a guest’s music, third-party footage or all underlying material.`,[],{sources:['copyrightLicence']}),
 sec('Do not build a campaign around a seconds rule',`The published Section 52 text includes fair-dealing purposes such as research, criticism or review, and reporting current events, subject to its provisions. It does not create a universal safe duration for promotional clipping. A short extract is not automatically exempt, and calling a campaign educational does not settle the legal question.

If you intend to rely on an exception, record the actual purpose, the source, what is reproduced and why that amount is necessary, then obtain appropriate case-specific legal review. Do not import a simplified United States fair-use checklist and present it as a complete Indian legal test. For ordinary promotional repurposing, obtaining a suitable licence is generally a more workable operational starting point than asking every participant to make their own exception assessment.`,[],{sources:['copyrightExceptions']}),
 sec('Map each element to the permission needed',`A podcast clip may combine the host’s recording, a guest interview, background music, a brand mark and an inserted chart. Identify these elements separately. A source owner may have rights for their original publication but limited permission for third-party advertising, paid distribution or editing. Ask about the intended reuse rather than requesting a vague assurance that the source is original.

Use a clearance status that can be understood by the editor: cleared for this use, excluded, or pending clarification. Pending material should not enter the approved campaign library. Where replacement is practical, a new graphic or appropriately licensed audio track may remove an unresolved element. Replacement should improve the record as well as the export; keep the old version out of the publishable folder.`,[],{table:table(['Element to inspect','Question for the supplier','Record to retain'],[['Main recording','Who can authorise edited redistribution?','Written permission tied to source ID'],['Guest contribution','Does the agreement cover this reuse?','Relevant release or authorised confirmation'],['Music or sampled audio','Does the licence cover this platform and use?','Licence scope and restrictions'],['Slides, images and inserts','Who owns the third-party material?','Clearance or replacement decision'],['Customer information','Is disclosure authorised and necessary?','Redaction or approval record']])}),
 sec('Specify the campaign’s permitted use',`Describe the allowed edits, publication accounts, platforms, territory, term and commercial purpose. Include whether participants can add commentary, translate captions, use paid promotion or retain clips in portfolios. Identify any prohibited claims, sensitive passages or required credits. This is a scope checklist to discuss with the rights holder, not a ready-made enforceable contract.

Consider the end of the campaign. Must participants remove posts, can existing approved posts remain, and what happens if permission is withdrawn or a source correction is needed? Assign somebody who can reach the relevant account owners. A licence record is much more useful when its conditions are connected to the actual source files and posted versions.`,[],{links:[link('creator-clipping-brief-template-india','the campaign brief template')]}),
 sec('Use a blank permissions register',`Create the register before files are shared broadly. Start with source ID, file version, rights contact, authorised use, excluded elements, evidence location, expiry or review date and the person responsible for clarification. Avoid placing private contracts or personal contact information in a publicly accessible campaign channel.

A demonstration entry could read: source demo-01; fictional interview extract; permission pending; music excluded; publication blocked until review. This example deliberately records no completed clearance. In a real project, replace every demonstration field with actual evidence. Do not prefill a new customer’s register with sample approvals, and do not convert a conversation summary into a signed licence record.`,[],{table:table(['Register field','What it should answer'],[['Source and version','Which exact file is covered?'],['Authorising party','Who grants the relevant rights?'],['Use and accounts','What distribution is permitted?'],['Exclusions','Which elements or passages stay out?'],['Evidence location','Where is the actual permission stored?'],['Term and owner','When must it be reviewed and by whom?']])}),
 sec('Give editors a source-specific clearance brief',`Editors need actionable instructions, not a folder labelled approved with no explanation. Attach the source ID, permitted passages, required credits and excluded elements to the editing task. If captions are translated, identify who approves meaning. If a guest corrects a statement, specify the replacement wording or source passage and withdraw the old cut.

Require each submission to reference the source and exported version. When a rights condition changes, you can then find affected edits and public links. Keep permission status separate from creative approval: an attractive edit can still be blocked for unresolved rights, while a cleared source may still need substantial editorial work. This separation reduces accidental publication during a revision cycle.`,[],{links:[link('good-clip-submission-format','traceable clip submissions')]}),
 sec('Review meaning, privacy and commercial claims',`A cut can preserve every spoken word while changing the meaning through omissions, order or a misleading hook. Compare the short extract with the surrounding conversation. Preserve relevant conditions, uncertainty and who is making the statement. A speaker discussing a possible result should not become a thumbnail promising a guaranteed outcome.

Also inspect private information, identifiable customer records, screens, location details and claims about third parties. Rights clearance does not automatically settle privacy, advertising or reputational questions. Escalate sensitive material to the person responsible for the campaign and obtain appropriate professional review where needed. Keep a written decision explaining the allowed version rather than asking an editor to guess what is acceptable.`,[],{links:[link('brand-safety-checklist-for-clippers','brand-safety review'),link('asci-disclosure-guide-paid-creator-clips-india','paid clip disclosure planning')]}),
 sec('Keep YouTube claims separate from legal ownership',`YouTube describes Content ID claims and copyright removal requests as different processes. Depending on the claim and the content, a claim can affect availability or monetisation; a removal request can lead to a strike. A claim is not a complete legal ruling on ownership, and the absence of one does not prove that every right is cleared.

Inspect the actual notice in Studio, the affected segment and the named claimant. Preserve the licence evidence and notify the campaign owner before taking action. Do not tell every participant to dispute automatically, or claim that attribution alone is a valid response. Use the platform’s current process only when the account owner understands the basis and consequences of the action.`,[],{sources:['youtubeClaims','youtubeCopyright']}),
 sec('Separate permission from channel monetisation',`A rights holder may permit a clip while the destination platform has separate eligibility conditions for monetisation, paid promotion or account participation. YouTube’s reused-content policy is distinct from copyright permission. A campaign fee paid by a sponsor is also different from advertising revenue paid through a platform programme.

Before describing a campaign as monetisable, name which revenue mechanism you mean and what has actually been verified. Do not imply that a written source licence guarantees YouTube Partner Program acceptance. Document permission, editorial contribution and the payment agreement as separate records so that a participant can understand the remaining uncertainties.`,[],{sources:['youtubeReuse'],links:[link('youtube-reused-content-rules-indian-clippers','YouTube reused-content and monetisation rules')]}),
 sec('Prepare a correction and takedown procedure',`List a campaign contact for rights concerns and keep a map from source versions to published links. When a credible issue is reported, preserve the notice, identify affected posts and route it to the responsible account owners. Depending on the issue and appropriate advice, pause further publication while the concern is assessed.

Track the request, decision, account response and final status. If a clip is replaced, mark the old version withdrawn and keep evidence of the change. Payment treatment for already completed work should follow the accepted agreement rather than being improvised after the event. A well-run correction process protects the integrity of the source record and helps prevent the same disputed material being reposted.`),
 sec('Resolve the final clearance decision explicitly',`Use a release checkpoint: every published cut has an identified source, a recorded permission basis, a cleared export and a named account owner. If one element remains uncertain, record the blocker and the next responsible action. A status should reflect actual review, not a deadline-driven assumption.

Complex cases can include third-party footage, disputed ownership, music licences, news extracts, paid endorsements and sensitive personal information. Obtain qualified legal or specialist review for the actual case. The purpose of the workflow is to make that review possible with organised facts, not to replace it. Commercial clipping becomes easier to govern when the team can explain exactly what it is authorised to use.`)
 ],faq:[
 ['Is it legal to clip a public YouTube video in India?', 'Public availability does not by itself grant edited redistribution rights. Identify the rights holder, planned use and applicable permission or exception. A public interview can contain separately controlled music or guest material. For a commercial campaign, obtain a suitable written permission record and resolve excluded elements before publishing.'],
 ['Does giving credit make a clip legal?', 'Credit identifies a source but does not itself establish a licence or satisfy every condition of an exception. Follow any required credit as part of the authorised use. Also check the permitted accounts, edits, platforms and commercial purpose. A credit line cannot fix a missing right to use third-party material.'],
 ['Can I safely use ten seconds of a song?', 'There is no universal ten-second permission rule for a clipping campaign. The recording and composition may involve separate rights, and a platform can also apply its own claim process. Use music whose licence actually covers the intended use or seek suitable clearance. Do not base a commercial workflow on duration alone.'],
 ['Is Indian fair dealing the same as US fair use?', 'They are different legal frameworks. The Indian published Act identifies relevant exceptions and conditions; a simplified US fair-use description is not a complete Indian assessment. If your project relies on an exception, obtain case-specific advice using the real source, purpose and proposed extract rather than a generic social-media slogan.'],
 ['Can a creator authorise all clips from their podcast?', 'They may be able to authorise rights they control, but the recording can include guest contributions, licensed music, slides or inserts with different conditions. Ask what is covered by the underlying agreements. Record any exclusions and supply a cleared source set rather than treating the creator’s ownership statement as universal clearance.'],
 ['Does permission guarantee YouTube monetisation?', 'No. Permission addresses the authorised reuse of material. YouTube monetisation has separate policies, and its reused-content review is distinct from copyright. A participant can also be paid by a campaign sponsor under a separate agreement. Name the revenue mechanism and verify its conditions rather than promising that every licensed clip earns platform revenue.']
 ]
});
