const {create,sec,table,link}=require('./helpers.cjs');
module.exports=create('how-to-choose-clipping-agency-india',{
 title:'How to choose a clipping agency in India: an evidence-based scorecard',
 dek:'Evaluate editorial judgment, language review, rights, account control and reporting through a common brief and a limited paid test.',
 description:'Choose a clipping agency in India using a common brief, portfolio evidence, language checks, a paid pilot and a weighted evaluation scorecard.',
 answer:'Choose a clipping agency by matching its contracted responsibilities to your actual bottleneck, then testing its work on an authorised source. Compare editorial quality, language accuracy, rights handling, approvals, distribution evidence, total cost and exit terms. A polished portfolio or promise of viral views is insufficient without evidence relevant to your project.',
 intent:'Give buyers a procurement and paid-pilot process with a scorecard, rather than another list of supposedly best agencies.',section:'guides',
 sections:[
 sec('Identify the problem you want the agency to own',`An agency may edit files, develop hooks, coordinate participants, publish on your accounts or report campaign outcomes. These are different responsibilities. List which part of your current workflow is failing: source selection, editing capacity, language review, distribution or operational coordination. Ask the supplier to state its responsibility for that bottleneck in writing.

If your team can publish consistently but cannot find strong moments, buying more exports may not solve the problem. If your content is already well edited but reaches the wrong audience, examine distribution and destination fit. A useful clipping agency in India should be evaluated against the work you need handled, including the language and review constraints of that work.`,[],{links:[link('managed-clipping-campaign-vs-hiring-freelance-editors','managed campaigns and freelance editing')]}),
 sec('Write one brief for every shortlisted supplier',`Use the same cleared source, audience, destination, language and requested deliverables across the shortlist. Include the claims that must remain qualified, forbidden passages and an example of the intended tone. Describe what acceptance means and which evidence you expect. This lets you compare how each supplier interprets the task rather than comparing unrelated portfolio highlights.

Ask suppliers to identify blockers before quoting. A recording with unclear rights or poor audio may need preparation. A team that points this out is giving you useful information. Record each assumption, exclusion and proposed alternative beside the quote. Keep the source access limited to the evaluation and avoid sharing sensitive customer material unnecessarily.

Blank request wording to adapt: please quote for the attached authorised source and audience brief; state the proposed deliverables, language reviewer, included revisions, approval schedule, distribution responsibility, evidence export, full cost and exclusions. Identify any source or access blocker before production, and propose a limited paid pilot. Fill in the actual source, dates and scope before sending; this is a template, not a request already sent to a supplier.`,[],{links:[link('creator-clipping-brief-template-india','the briefing template')]}),
 sec('Inspect a portfolio as an evidence record',`Ask what the agency actually contributed to a sample: selecting the moment, editing, writing captions, publishing or coordinating a campaign. A public post does not establish that one supplier controlled every part of its performance. Request source-to-export explanation and permission to view relevant work rather than copying another client’s confidential dashboard.

Look for preserved context, an understandable opening and a coherent end. Check whether the captions match the speaker and whether graphics clarify the idea. Ask how a correction was handled. A modest sample with a clear explanation of editorial choices may reveal more than a compilation of high-view posts with no source, role or measurement dates.`,[],{table:table(['Portfolio claim','Evidence to request','Question it answers'],[['We edited this clip','Source excerpt and contribution explanation','What work did the team perform?'],['This campaign reached viewers','Metric definition, date and account scope','What was actually measured?'],['We handle language quality','Review process and corrected sample','Who checks meaning?'],['We manage campaigns','Redacted workflow and reconciliation example','Which operational tasks are owned?']])}),
 sec('Test language accuracy with meaningful details',`Include passages containing names, numbers, mixed-language phrases and a qualification that matters. Ask who reviews the required language and how corrections return to the editor. Do not assess Hindi, Tamil or another language solely by the visual neatness of a caption style. Accurate meaning, natural phrasing and readable line breaks are different qualities.

A practical evaluation can ask the agency to explain one ambiguous phrase and provide its final caption decision. Have your own fluent reviewer inspect it if available. Record disagreements and how they were resolved. This is a project-specific test, not a certification that the team is fluent in every regional language it lists on a website.`,[],{links:[link('regional-language-clipping-india','regional language review'),link('accessible-captions-short-form-clips-india','caption accuracy and accessibility')]}),
 sec('Evaluate rights and brand-safety ownership',`Ask who prepares the source clearance record and who approves sensitive claims before publication. A supplier should explain how it keeps excluded music, private information and disputed passages out of exports. Clarify who handles a rights complaint and how affected public links are located. The answer should fit the source and campaign, not just state that copyright is the client’s problem.

Contract responsibilities do not eliminate the need to supply truthful information and appropriate permissions. If a supplier recommends removing credits, hiding paid promotion or posting unapproved source material, treat that as a blocker. Resolve rights and claim-review questions before scoring creative quality. A visually strong edit is not enough to justify publication.`,[],{links:[link('is-video-clipping-legal-in-india','rights clearance'),link('brand-safety-checklist-for-clippers','brand-safety decisions')]}),
 sec('Ask how distribution will be evidenced',`If the agency offers distribution, request the permitted account list, public-link record, measurement window and explanation of the metric. Ask how it distinguishes approved placements from proposed ones and what happens when a post is deleted. If it reports downstream traffic, request the naming convention and the destination’s measurement basis.

BCG’s 2025 India creator-economy research highlights measurement and authenticity concerns. That is context for asking better questions, not proof that a shortlisted supplier’s results are wrong. Inspect the actual evidence. A summed cross-platform view total should not be called unique reach, and a sales increase during the campaign should not be presented as caused by it without a suitable method.`,[],{sources:['indiaCreators'],links:[link('clipping-campaign-case-study-evidence-template','auditable campaign case studies')]}),
 sec('Compare the complete cost and change rules',`Separate source preparation, editing, language review, publication, administration, tools and participant payouts. Confirm any minimum term and the handling of unused deliverables. Ask which revisions are included and how an approved scope changes. A monthly fee with unclear obligations is difficult to compare with an itemised batch quote.

Include the time your own team must spend reviewing and resolving questions. A supplier who needs constant interpretation of the same brief may create costs outside its invoice. Compare quotes using a common project subtotal and clearly listed exclusions. The scorecard below deliberately provides no market-price threshold; price suitability depends on the actual project and verified terms.`,[],{links:[link('clipping-campaign-pricing-budget-india','budget and quotation comparison')]}),
 sec('Use a weighted scorecard with evidence attached',`The following weights are an illustrative starting point, not a measured procurement standard. Score each category from zero to five only when you have relevant evidence. Zero means no adequate evidence or an unacceptable result; five means the requirement is strongly demonstrated for this project. Mark missing evidence as unverified rather than assuming average competence.

Multiply each score by its percentage weight and divide by five; sum the results for an illustrative score out of 100. Set non-negotiable blockers separately. A team cannot compensate for unresolved rights or unsafe account access by scoring highly on design. Adjust weights before evaluating suppliers so that the preferred agency does not determine the scoring rules.`,[],{table:table(['Illustrative criterion','Weight','Evidence to attach'],[['Editorial judgment and context','25%','Source-to-export explanation'],['Required language and captions','20%','Reviewed pilot with correction log'],['Rights and claim controls','15%','Source-specific clearance process'],['Review and operational reliability','15%','Pilot response and acceptance record'],['Reporting and distribution evidence','15%','Metric definitions and exportable records'],['Total cost and exit clarity','10%','Comparable quote and ownership terms']])}),
 sec('Run a paid pilot that answers a real question',`Agree a limited fee and scope, use authorised material and choose a deliverable that represents the work you will later need. Avoid asking for a large unpaid batch. Include one feedback round and document the response. The test should reveal editorial reasoning, interpretation of the brief and the reliability of handoff, not just the ability to produce one decorative edit.

Hypothetical pilot: a creator asks for two different hooks from one cleared interview moment, with accurate bilingual captions and a written explanation of the chosen cut. The creator then checks whether both versions preserve a crucial qualification. This is an evaluation design, not a reported RiseKlix engagement or evidence that two clips are a universal ideal pilot.`,[],{table:table(['Pilot stage','Observation'],[['Before production','Does the team identify ambiguity and source constraints?'],['First delivery','Does the export meet the agreed audience and context?'],['Feedback','Are corrections understood and applied consistently?'],['Handoff','Are versions, files and evidence complete?'],['Closeout','Are acceptance and payment recorded accurately?']])}),
 sec('Clarify account control, files and the exit process',`Confirm who owns publishing accounts and who can grant or revoke access. Prefer permissions appropriate to the task and record who administers them. Ask what files, caption tracks, source maps and reporting exports you receive. A project can become hard to transfer if the only usable files or records remain inside a supplier’s private workspace.

Define what happens when the engagement ends: final deliverables, outstanding approvals, unsettled amounts, removal of access and any retention or deletion obligations. Check portfolio-use permission too. An exit process is useful even for a good relationship because teams and priorities change. Keep it proportionate to the scope rather than accepting a vague promise that everything will be handed over later.`),
 sec('Recognise promises that need stronger evidence',`Guaranteed virality, guaranteed revenue and unexplained claims of organic reach deserve careful scrutiny. Ask what is being guaranteed, under what conditions and what remedy is written into the agreement. Do not infer that a dramatic claim is validated because the agency has a polished website or recognisable client logos.

Other concerns include refusal to define metrics, pressure to share credentials, unclear participant payments and public results with no dates or denominators. These are reasons to request evidence or decline a particular arrangement. Avoid publishing an unsupported accusation about the supplier. Record the specific missing requirement and use the same standard across every shortlisted team.`,[],{links:[link('how-to-check-clipping-campaign-legit-india','offer verification and evidence preservation')]}),
 sec('Choose the next commitment from the pilot record',`After scoring, write a short decision explaining the strongest evidence, remaining uncertainties and proposed scope. Compare the agency’s contribution with what your team can do internally. If the pilot succeeds only after extensive unpriced client intervention, include that effort in the decision. A good supplier should make the next workflow clearer.

Expand in a way that tests the remaining uncertainty: a new source, another language or additional distribution, rather than all three at once. Retain acceptance records and review the engagement at an agreed checkpoint. Choosing a clipping agency is an ongoing allocation of responsibilities. The useful authority comes from evidence relevant to your work, not a universal best-agency label.`)
 ],faq:[
 ['What should I ask a clipping agency before hiring it?', 'Ask which tasks it owns, who checks language and rights, how acceptance works, what distribution evidence you receive, what the full cost includes and how you exit. Give every supplier the same authorised source brief. Request evidence linked to those requirements rather than accepting a general promise to grow your brand.'],
 ['How many portfolio samples should I review?', 'There is no universal number. Review enough relevant samples to understand source selection, editing contribution, language accuracy and correction handling. A few well-explained examples can be more informative than a large showreel. Use a limited paid pilot to evaluate the actual team and process intended for your project.'],
 ['Should I choose the cheapest agency?', 'Compare full scope, exclusions and client review effort first. A low price can be suitable for a narrow, clear task, but hidden source preparation, language review or rework may change the total. Evaluate affordability alongside evidence of the required quality and responsibilities. The scorecard does not establish an Indian market rate.'],
 ['Can an agency guarantee viral clips?', 'Ask for a precise written definition and conditions if a supplier uses that phrase. Audience response and platform distribution are uncertain. A contractual remedy is different from evidence that a particular clip will go viral. Base your buying decision on controllable deliverables, relevant audience measures and a bounded pilot.'],
 ['Do I need a local Indian agency?', 'Location can affect communication, language review and working hours, but it does not prove competence. Evaluate the languages, audience context, invoicing arrangement and support your project actually needs. An Indian office alone does not demonstrate regional-language accuracy or trustworthy distribution. Inspect the team’s work and accepted responsibilities.'],
 ['What if two agencies receive similar scores?', 'Compare the evidence behind the scores and the unresolved risks rather than treating a small numerical difference as decisive. Consider the paid pilot’s correction burden, handoff quality and fit with your internal team. If necessary, run a narrower follow-up test addressing the specific uncertainty before making a larger commitment.']
 ]
});
