// Contextual routes from the established library to distinct new research topics.
module.exports={
 'why-india-needs-clipping-networks':[['does-clipping-work-in-india','a project-specific Indian clipping feasibility test']],
 'clipping-side-hustle-india':[['does-clipping-work-in-india','feasibility and sustainable work'],['how-to-check-clipping-campaign-legit-india','checking a campaign offer']],
 'how-to-become-a-clipper-india':[['how-to-check-clipping-campaign-legit-india','campaign legitimacy checks'],['accessible-captions-short-form-clips-india','accurate and accessible captions']],
 'how-much-do-indian-clippers-earn':[['clipping-campaign-pricing-budget-india','rates, caps and budget arithmetic']],
 'how-to-plan-a-creator-clipping-campaign-india':[['clipping-campaign-pricing-budget-india','a full campaign budget'],['does-clipping-work-in-india','a feasibility decision record']],
 'creator-clipping-campaign-roi-calculator-india':[['clipping-campaign-pricing-budget-india','cost buckets and reconciliation']],
 'creator-clipping-brief-template-india':[['is-video-clipping-legal-in-india','a source permissions register']],
 'creator-content-library-guide-india':[['is-video-clipping-legal-in-india','source-by-source rights clearance']],
 'disclosure-rules-for-paid-clips-india':[['is-video-clipping-legal-in-india','permissions alongside disclosure']],
 'clipping-campaign-fraud-prevention':[['how-to-check-clipping-campaign-legit-india','participant offer verification']],
 'upi-payouts-for-clipper-campaigns':[['how-to-check-clipping-campaign-legit-india','counterparty and settlement checks']],
 'creator-clipping-agency-vs-clipping-marketplace':[['how-to-choose-clipping-agency-india','an agency procurement scorecard'],['ai-clipping-tools-vs-clipping-marketplaces','editing software and campaign responsibilities']],
 'managed-clipping-campaign-vs-hiring-freelance-editors':[['how-to-choose-clipping-agency-india','a limited paid agency test']],
 'riseklix-vs-traditional-social-media-agency':[['how-to-choose-clipping-agency-india','evaluating a supplier against your actual brief']],
 'ai-tools-for-clipping-workflows':[['ai-clipping-tools-vs-clipping-marketplaces','tools, marketplaces and managed services']],
 'best-clipping-platforms-india':[['ai-clipping-tools-vs-clipping-marketplaces','a category and responsibility matrix']],
 'clipping-net-alternative-india':[['ai-clipping-tools-vs-clipping-marketplaces','choosing the correct product category']],
 'clipping-for-youtube-channels-india':[['youtube-reused-content-rules-indian-clippers','reused content, permission and channel monetisation']],
 'youtube-shorts-clipper-guide-india':[['youtube-reused-content-rules-indian-clippers','separating channel eligibility from campaign pay']],
 'youtube-shorts-clipping-for-podcasts':[['youtube-reused-content-rules-indian-clippers','documenting an original channel contribution']],
 'how-to-track-clipping-roi':[['utm-tracking-clipping-campaigns-india','UTM setup and reconciliation'],['clipping-campaign-case-study-evidence-template','an evidence-based closeout report']],
 'clipping-campaigns-saas-founders-india':[['utm-tracking-clipping-campaigns-india','tagged destination visits and attribution limits']],
 'clipping-for-d2c-brands-india':[['utm-tracking-clipping-campaigns-india','tracking visits without overstating sales causation']],
 'hinglish-clipping-guide':[['accessible-captions-short-form-clips-india','a mixed-language caption correction exercise']],
 'regional-language-clipping-india':[['accessible-captions-short-form-clips-india','language-aware accessibility review']],
 'brand-safety-checklist-for-clippers':[['accessible-captions-short-form-clips-india','caption meaning and visual-context checks']],
 'how-riseklix-verifies-clip-views-public-links':[['clipping-campaign-case-study-evidence-template','metric definitions and a case-study evidence register']],
 'creator-clipping-india-operating-manual-2026':[['clipping-campaign-case-study-evidence-template','an honest campaign reporting template']]
};
