module.exports={
 'what-is-a-clipper':[['video-clipping-vs-video-editing-vs-ugc-india','clipping, editing and new creator production']],
 'creator-clipping-vs-influencer-marketing-india':[['video-clipping-vs-video-editing-vs-ugc-india','source repurposing and commissioned UGC']],
 'riseklix-vs-influencer-marketing-agency-india':[['video-clipping-vs-video-editing-vs-ugc-india','comparing the actual production deliverable']],
 'instagram-reels-clipper-guide-india':[['instagram-reels-vs-youtube-shorts-clipping-india','a matched-source Reels and Shorts test']],
 'youtube-shorts-clipper-guide-india':[['instagram-reels-vs-youtube-shorts-clipping-india','comparing platform fit and metrics']],
 'clipping-campaigns-for-indian-podcasters':[['instagram-reels-vs-youtube-shorts-clipping-india','platform selection for a source library']],
 'discord-clipping-network-vs-saas-clipping-platform':[['creator-owned-vs-participant-accounts-clipping','account control and audience ownership']],
 'how-to-brief-50-clippers':[['creator-owned-vs-participant-accounts-clipping','participant publication responsibilities']],
 'is-video-clipping-legal-in-india':[['creator-owned-vs-participant-accounts-clipping','source permission and publishing identity']],
 'clipping-for-d2c-brands-india':[['utm-links-vs-coupon-codes-clipping-attribution','tagged traffic, code use and evidence overlap']],
 'utm-tracking-clipping-campaigns-india':[['utm-links-vs-coupon-codes-clipping-attribution','complementary attribution methods']],
 'how-to-track-clipping-roi':[['utm-links-vs-coupon-codes-clipping-attribution','deduplicating observed commercial outcomes']],
 'what-counts-as-an-approved-clip':[['clipping-submission-rejected-fix-appeal','diagnosing and reviewing a rejection']],
 'good-clip-submission-format':[['clipping-submission-rejected-fix-appeal','correction and appeal evidence']],
 'clipping-campaign-fraud-prevention':[['clipping-submission-rejected-fix-appeal','separating review disagreements from unsafe requests']],
 'how-to-become-a-clipper-india':[['paid-clipper-test-assignment-scorecard','a bounded paid test and quality rubric']],
 'clipper-portfolio-guide-india':[['paid-clipper-test-assignment-scorecard','demonstrating source judgment in a paid assignment']],
 'how-to-choose-clipping-agency-india':[['paid-clipper-test-assignment-scorecard','a practical production-quality test']],
 'how-to-plan-a-creator-clipping-campaign-india':[['clipping-campaign-landing-page-checklist','the destination-readiness checklist']],
 'clipping-for-saas-founders-india':[['clipping-campaign-landing-page-checklist','a clear product destination and real enquiry handling']],
 'does-clipping-work-in-india':[['clipping-campaign-landing-page-checklist','testing the full campaign journey']],
 'youtube-reused-content-rules-indian-clippers':[['facebook-reels-original-content-clipping-india','Facebook-specific originality guidance']],
 'brand-safety-checklist-for-clippers':[['facebook-reels-original-content-clipping-india','contribution and account review on Facebook']],
 'best-clipping-platforms-for-indian-creators':[['facebook-reels-original-content-clipping-india','Facebook publishing and evidence questions']],
 'stream-clipper-guide-india':[['twitch-clips-permissions-campaign-guide','Twitch creation and sharing permissions']],
 'clipping-campaigns-gaming-streamers-india':[['twitch-clips-permissions-campaign-guide','source-to-post records for Twitch moments']],
 'creator-content-library-guide-india':[['twitch-clips-permissions-campaign-guide','native clips, exports and third-party links']],
 'what-makes-a-clip-go-viral-india':[['why-viral-clips-dont-build-creator-audience','attention and durable audience continuity']],
 'podcast-clip-hooks-that-work-in-india':[['why-viral-clips-dont-build-creator-audience','connecting the hook to a useful creator library']],
 'founder-led-brand-clipping-guide':[['why-viral-clips-dont-build-creator-audience','building a coherent audience proposition']]
};
