import {chromium} from '/Users/satwikkumar/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
import editorial from '../src/content.cjs';
const root=fileURLToPath(new URL('../',import.meta.url)),routes=JSON.parse(fs.readFileSync(path.join(root,'docs/route-manifest.json'),'utf8'));
const articleByFile=new Map(editorial.articles.map(a=>[`${a.section}/${a.slug}.html`,a]));
const origin='http://127.0.0.1:8770',production='https://clip.riseklix.com';
const issues=[],results=[],errors=[],requests=[];
const browser=await chromium.launch({headless:true,channel:'chrome'});
const pages=await Promise.all(Array.from({length:4},()=>browser.newPage({viewport:{width:1440,height:1000}})));
for(const page of pages){page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(origin)&&r.status()>=400)requests.push([r.url(),r.status()]);});}
const originalRoutes=JSON.parse(fs.readFileSync(path.join(root,'docs/original-route-manifest.json'),'utf8'));
const additions=editorial.articles.filter(a=>a.researchedArticle).map(a=>`${a.section}/${a.slug}.html`);
assert.deepEqual([...routes].sort(),[...originalRoutes,...additions].sort(),'All original URLs plus all researched article cohorts are present');
let next=0;
await Promise.all(pages.map(async page=>{while(next<routes.length){const file=routes[next++],route='/'+file.replace(/index\.html$/,'');await page.setViewportSize({width:1440,height:1000});const res=await page.goto(origin+route);await page.evaluate(async()=>{await document.fonts.ready;await Promise.all(Array.from(document.images).map(x=>{x.loading='eager';return x.decode().catch(()=>{})}))});const data=await page.evaluate(()=>{
 const schema=Array.from(document.querySelectorAll('script[type="application/ld+json"]')).map(x=>JSON.parse(x.textContent));
 const links=Array.from(document.querySelectorAll('a[href]')).map(x=>x.getAttribute('href'));
 const inputs=Array.from(document.querySelectorAll('input,select,textarea')).filter(x=>!x.labels?.length&&!x.getAttribute('aria-label')).map(x=>x.outerHTML);
 return {title:document.title,description:document.querySelector('meta[name=description]')?.content,canonical:document.querySelector('link[rel=canonical]')?.href,h1s:document.querySelectorAll('h1').length,fragmentIds:Array.from(document.querySelectorAll('[id]')).map(el=>el.id),schemas:schema,links,unlabelled:inputs,images:Array.from(document.images).filter(x=>!x.complete||x.naturalWidth===0).map(x=>x.src),missingAlt:Array.from(document.images).filter(x=>!x.hasAttribute('alt')).map(x=>x.src),desktopOverflow:document.documentElement.scrollWidth>innerWidth+1,mainText:document.querySelector('main').innerText,articleHeadings:Array.from(document.querySelectorAll('[id^="section-"] h2')).map(x=>x.textContent),faqQuestions:Array.from(document.querySelectorAll('#questions summary')).map(x=>{const copy=x.cloneNode(true);copy.querySelectorAll('[aria-hidden="true"]').forEach(icon=>icon.remove());return copy.textContent.trim()})};
 });
 if(res.status()!==200)issues.push([file,'HTTP '+res.status()]);if(data.h1s!==1)issues.push([file,'H1 count '+data.h1s]);if(!data.title||!data.description)issues.push([file,'Missing metadata']);if(data.canonical!==production+route)issues.push([file,'Canonical differs']);if(data.unlabelled.length||data.missingAlt.length||data.images.length)issues.push([file,'Labels or images',data.unlabelled,data.missingAlt,data.images]);if(data.desktopOverflow)issues.push([file,'Desktop overflow']);if(/structured to be citable|Use this aeo|matters because Indian creators/i.test(data.mainText))issues.push([file,'Boilerplate remains']);
 const article=articleByFile.get(file);
 if(article){
  if(JSON.stringify(data.articleHeadings)!==JSON.stringify(article.sections.map(s=>s.heading)))issues.push([file,'Rendered article sections differ from authored text']);
  if(JSON.stringify(data.faqQuestions)!==JSON.stringify(article.faq.map(q=>q[0])))issues.push([file,'Rendered FAQs differ from authored text']);
  for(const s of article.sections)for(const p of s.paragraphs)if(!data.mainText.includes(p))issues.push([file,'Authored paragraph absent from rendered page',s.heading]);
 }
 for(const s of data.schemas.flatMap(x=>x['@graph']||[]))if(['FAQPage','HowTo'].includes(s['@type']))issues.push([file,'Unnecessary schema '+s['@type']]);
 for(const link of data.links){if(!link||/^https?:|^mailto:|^tel:/.test(link))continue;const u=new URL(link,origin+route);let target=decodeURIComponent(u.pathname).slice(1);if(!target||target.endsWith('/'))target+='index.html';if(!fs.existsSync(path.join(root,'public',target)))issues.push([file,'Missing link',link]);if(u.hash&&u.pathname===route){const exists=data.fragmentIds.includes(decodeURIComponent(u.hash.slice(1)));if(!exists)issues.push([file,'Missing fragment',link]);}}
 await page.setViewportSize({width:390,height:844});const mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(mobileOverflow)issues.push([file,'390px overflow']);await page.setViewportSize({width:320,height:800});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))issues.push([file,'320px overflow']);
 results.push({file,status:res.status(),title:data.title,description:data.description,h1:data.h1s,canonical:data.canonical,words:data.mainText.split(/\s+/).length,desktopOverflow:data.desktopOverflow,mobileOverflow});
 }}));
const page=pages[0];await page.setViewportSize({width:390,height:844});await page.goto(origin+'/');await page.locator('.menu-toggle').click();assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');assert.equal(await page.locator('#site-nav').isVisible(),true);await page.keyboard.press('Escape');assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'false');
await page.selectOption('.theme-select','dark');await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.selectOption('.theme-select','system');await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});assert.equal(await page.locator('html').evaluate(x=>getComputedStyle(x).getPropertyValue('--bg').trim()),'#171717');assert.equal(await page.locator('html').evaluate(x=>getComputedStyle(x).scrollBehavior),'auto');await page.emulateMedia({colorScheme:'light',reducedMotion:'no-preference'});
await page.goto(origin+'/resources/');
const latest=editorial.articles.filter(a=>a.researchBatch===Math.max(...editorial.articles.map(a=>a.researchBatch||0)));
const latestRoutes=latest.map(a=>`/${a.section}/${a.slug}.html`);
assert.deepEqual(await page.locator('#resource-grid .resource-card').evaluateAll((cards,count)=>cards.slice(0,count).map(card=>card.querySelector('a').getAttribute('href')),latest.length),latestRoutes,'Latest research cohort appears first');
assert.equal(await page.locator('.reading-paths .route-body li a').count(),9,'Nine curated reading steps are present in static HTML');
assert.equal(await page.locator('.library-route-disclosure').evaluate(el=>el.open),false,'Curated paths leave direct library search available by default');
await page.locator('#resource-search').fill('zzzzz-no-match');assert.equal(await page.locator('.empty-state').isVisible(),true);await page.locator('#clear-filters').click();assert.equal(await page.locator('#resource-grid .resource-card:visible').count(),editorial.articles.length);await page.selectOption('#resource-category','compare');assert.equal(await page.locator('#resource-grid .resource-card:visible').count(),editorial.articles.filter(a=>a.section==='compare').length);await page.locator('#resource-search').fill('clipping.net');assert.equal(await page.locator('#resource-grid .resource-card:visible').count(),1);
await page.goto(origin+'/blog/creator-clipping-campaign-roi-calculator-india.html');assert.equal(await page.locator('[name=cost]').inputValue(),'');await page.locator('[name=cost]').fill('10000');await page.locator('[name=views]').fill('50000');await page.locator('[name=revenue]').fill('15000');await page.locator('#roi-form button[type=submit]').click();assert.match(await page.locator('#roi-output').innerText(),/50%/);assert.match(await page.locator('#roi-output').innerText(),/₹200/);await page.locator('[name=views]').fill('0');await page.locator('#roi-form button[type=submit]').click();assert.match(await page.locator('#roi-output').innerText(),/Undefined/);await page.locator('#roi-form button[type=reset]').click();assert.equal(await page.locator('[name=cost]').inputValue(),'');
await page.goto(origin+'/guides/how-much-do-clippers-make-india.html');await page.locator('[name=views]').fill('50000');await page.locator('[name=rate]').fill('100');await page.locator('[name=fee]').fill('10');await page.locator('[name=cap]').fill('3000');await page.locator('#earnings-form button[type=submit]').click();assert.match(await page.locator('#earnings-output').innerText(),/₹3,000/);assert.match(await page.locator('#earnings-output').innerText(),/₹2,700/);
await page.goto(origin+'/contact/');await page.locator('.campaign-workbook>summary').click();const form=page.locator('#brief-form');const values={project:'TEST DEMONSTRATION',goal:'Test only',language:'Test audience',sources:'https://example.com/source',platform:'Test platform',budget:'Test only',notes:'Demonstration for browser verification; not a campaign.'};for(const [name,value]of Object.entries(values))await form.locator(`[name=${name}]`).fill(value);await form.locator('[type=submit]').click();assert.match(await form.locator('.brief-output').inputValue(),/TEST DEMONSTRATION/);await page.reload();await page.locator('.campaign-workbook>summary').click();assert.equal(await form.locator('[name=project]').inputValue(),'TEST DEMONSTRATION');const downloadPromise=page.waitForEvent('download');await form.locator('[data-download-brief]').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'riseklix-campaign-brief.txt');await form.locator('[type=reset]').click();await page.reload();assert.equal(await form.locator('[name=project]').inputValue(),'');assert.equal(await page.locator('#campaign-enquiry [name=email]').inputValue(),'');assert.equal(await page.locator('#talent-intro [data-clipper-entry]').count(),1);
// Same content and navigation remain available without JavaScript.
const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}}),np=await nojs.newPage();await np.goto(origin+'/guides/creator-clipping-campaign-guide-india.html');assert.equal(await np.locator('h1').count(),1);assert.equal(await np.locator('#site-nav').isVisible(),true);assert.equal(await np.locator('#direct-answer').isVisible(),true);await np.goto(origin+'/blog/creator-clipping-brief-template-india.html');assert.equal(await np.locator('[href="/assets/campaign-brief-template.txt"]').count(),1);
const titles=results.map(x=>x.title);assert.equal(new Set(titles).size,titles.length,'Unique titles');const descriptions=results.map(x=>x.description);assert.equal(new Set(descriptions).size,descriptions.length,'Unique descriptions');assert.equal((fs.readFileSync(path.join(root,'public/sitemap.xml'),'utf8').match(/<loc>/g)||[]).length,routes.length);
const report={checkedAt:new Date().toISOString(),pages:results.length,articleDepthChecks:articleByFile.size,viewports:[1440,390,320],issues,pageErrors:errors,failedRequests:requests,interactions:['Mobile menu and Escape','Persistent dark theme','System theme follows OS','Reduced motion','Resource search and category filters','Latest cohort first and nine steps in three curated reading journeys','ROI arithmetic and zero views','Earnings fee and cap','Empty forms, draft restore, download and clear','No-JavaScript content and template fallback'],results:results.sort((a,b)=>a.file.localeCompare(b.file))};fs.writeFileSync(path.join(root,'docs/verification.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({pages:report.pages,articleDepthChecks:report.articleDepthChecks,issues,errors,requests,interactions:report.interactions},null,2));if(issues.length||errors.length||requests.length)process.exitCode=1;
