const discord='https://discord.gg/skQk3xZcRa';
const guide='/guides/how-to-become-a-clipper-india.html';
const icon='<svg width="19" height="19" viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false"><path d="M5 4h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H9l-6 3V6a2 2 0 0 1 2-2Z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/><path d="M8 10h.01M12 10h.01M16 10h.01" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>';
function joinLink(label='Join Discord',classes='button discord-button',extra=''){
 return `<a class="${classes}" href="${discord}" data-clipper-join ${extra}>${icon}<span>${label}</span><span aria-hidden="true">↗</span></a>`;
}
function startPanel(){return `<section class="clipper-start container" id="clipper-start" aria-labelledby="clipper-start-title"><div class="clipper-start-copy"><p class="eyebrow">For clippers & editors</p><h2 id="clipper-start-title">Your first step.<br><em>Join the Discord.</em></h2><p>Want to turn approved videos into short-form clips? Join Clip by RiseKlix to ask about current campaign requirements and how to get started.</p><div class="clipper-start-actions">${joinLink('Join Discord as a clipper')}<a class="text-link" href="${guide}">Read the beginner guide <span aria-hidden="true">→</span></a></div><p class="small clipper-expectation">You’ll continue in Discord. Sign in or create an account if asked. No website application form.</p></div><ol class="clipper-first-steps"><li><span aria-hidden="true">01</span><div><h3>Accept the server invite</h3><p>Check that the invite says “Clip by RiseKlix”, then continue in Discord.</p></div></li><li><span aria-hidden="true">02</span><div><h3>Follow the welcome instructions</h3><p>Read the server rules and complete any steps Discord or the community asks for.</p></div></li><li><span aria-hidden="true">03</span><div><h3>Check the brief before you edit</h3><p>Ask about available opportunities. Confirm eligibility, approved sources and payment terms first.</p></div></li></ol><p class="small clipper-availability">Campaign availability varies. Joining the community does not guarantee work or payment.</p></section>`;}
function guideEntry(){return `<section class="clipper-guide-entry" aria-labelledby="clipper-guide-join-title"><div><p class="eyebrow">Ready to join?</p><h2 id="clipper-guide-join-title">Start in the Discord community.</h2><p>You can join before reading this full guide. Accept the invite, follow the server instructions and ask about current campaign requirements.</p></div><div>${joinLink('Join Discord as a clipper')}<p class="small">If a new tab didn’t open, this link takes you directly to the invite.</p></div></section>`;}
const clipperSlugs=new Set(['how-to-become-a-clipper-india','what-is-a-clipper','clipping-side-hustle-india','freelance-clipper-guide-india','remote-clipping-jobs-india','clipper-portfolio-guide-india','how-much-do-clippers-make-india','how-much-do-indian-clippers-earn','best-editing-tools-for-clippers-india','best-free-tools-for-clippers-india','good-clip-submission-format','what-counts-as-an-approved-clip','clipping-submission-rejected-fix-appeal','paid-clipper-test-assignment-scorecard','youtube-shorts-clipper-guide-india','instagram-reels-clipper-guide-india','x-twitter-clipper-guide-india','tiktok-clipper-guide-india','stream-clipper-guide-india','accessible-captions-short-form-clips-india']);
function articleJoin(a){return clipperSlugs.has(a.slug)?`<section class="clipper-article-join" aria-label="Join the clipper community"><p class="eyebrow">Your next step</p><h2>Bring your questions to Discord.</h2><p>Ask about current briefs and requirements, or get context before your first edit.</p>${joinLink('Join Discord as a clipper')}<p class="small">Check campaign terms before starting work.</p></section>`:'';}
function hasClipperEntry(file){return file==='index.html'||clipperSlugs.has(file.split('/').at(-1).replace(/\.html$/,''));}
module.exports={joinLink,startPanel,guideEntry,articleJoin,hasClipperEntry};
