const input=(name,label,attrs='',hint='')=>`<div class="enquiry-field"><label for="enquiry-${name}">${label}</label>${hint?`<p class="field-hint" id="${name}-hint">${hint}</p>`:''}<input id="enquiry-${name}" name="${name}" ${attrs} aria-describedby="${hint?name+'-hint ':''}${name}-error"><p class="field-error" id="${name}-error" hidden></p></div>`;
module.exports=({breadcrumb,briefTool,discord,arrow})=>`<section class="campaign-hero container">${breadcrumb('Start a campaign')}<div class="campaign-title"><div><p class="eyebrow">A good campaign starts with a conversation</p><h1>Let’s start with<br><em>your story.</em></h1><p class="lead">Looking to run an Indian clipping campaign? Tell us what you want to promote. We’ll use your enquiry to discuss the right next step.</p></div><div class="campaign-note"><span class="eyebrow">The first cut / 01</span><p>An idea is enough.<br><strong>You can work out the details with us.</strong></p><a href="#campaign-intro">Tell us the idea ↓</a><a href="#talent-intro">Here to earn as a clipper? ↓</a></div></div></section>
<section class="campaign-layout container" aria-label="Campaign enquiry"><div class="enquiry-card" id="campaign-intro"><div class="enquiry-card-heading"><p class="eyebrow">Your campaign enquiry</p><h2>Tell us the idea.</h2><p>Just three things to get started: your name, email, and idea. Everything else is optional.</p></div>
<div id="enquiry-errors" class="enquiry-errors" tabindex="-1" aria-labelledby="enquiry-errors-title" hidden><h3 id="enquiry-errors-title">Check these details</h3><ul></ul></div>
<div id="enquiry-success" class="enquiry-success" tabindex="-1" aria-labelledby="enquiry-success-title" hidden><p class="eyebrow">Enquiry submitted</p><h2 id="enquiry-success-title">Your idea is on its way.</h2><p>Your enquiry was accepted for sending to the RiseKlix team. We’ll use the email you provided to reply. Delivery and a campaign agreement are still separate steps.</p><p class="small" data-enquiry-reference></p><div class="tool-actions"><a class="button outline" href="/guides/creator-clipping-campaign-guide-india.html">Read the campaign guide ${arrow}</a><button type="button" class="button quiet" data-new-enquiry>Start another enquiry</button></div></div>
<form id="campaign-enquiry" action="/api/campaign-enquiry" method="post"><div class="enquiry-person">${input('name','Your name','type="text" autocomplete="name" maxlength="80" required')}${input('email','Email to reply to','type="email" autocomplete="email" inputmode="email" maxlength="254" required')}</div>
<div class="enquiry-field"><label for="enquiry-goal">What would you like to promote?</label><p class="field-hint" id="goal-hint">A creator, brand, podcast, stream, product, or something else. Tell us what you hope the campaign will do.</p><textarea id="enquiry-goal" name="goal" rows="5" maxlength="4000" required aria-describedby="goal-hint goal-error"></textarea><p class="field-error" id="goal-error" hidden></p></div>
${input('sourceUrl','A link to your content or project (optional)','type="url" inputmode="url" maxlength="2048" placeholder="https://…"','A public link is useful. You can send approved source material later.')}
<details class="enquiry-context"><summary>Add a little context <span>(optional)</span><span aria-hidden="true">＋</span></summary><div class="enquiry-context-fields"><div class="enquiry-field"><label for="enquiry-budget">Budget (optional)</label><select id="enquiry-budget" name="budget" aria-describedby="budget-error"><option value="">Choose if you know</option><option value="Help me scope the budget">Not sure — help me scope it</option><option value="Under ₹25,000">Under ₹25,000</option><option value="₹25,000–₹75,000">₹25,000–₹75,000</option><option value="₹75,000–₹2,00,000">₹75,000–₹2,00,000</option><option value="Above ₹2,00,000">Above ₹2,00,000</option></select><p class="field-hint">Planning ranges only. Scope and pricing are discussed separately.</p><p class="field-error" id="budget-error" hidden></p></div>${input('audience','Audience or language (optional)','type="text" maxlength="200" placeholder="For example, Hindi-speaking gaming fans"')}${input('timing','When would you like to start? (optional)','type="text" maxlength="80" placeholder="For example, next month or still exploring"')}</div></details>
<div class="enquiry-trap" aria-hidden="true"><label for="enquiry-website">Leave this field empty</label><input id="enquiry-website" name="website" tabindex="-1" autocomplete="off"></div>
<p class="enquiry-privacy">When you send, your answers go to the RiseKlix team by email through Resend so we can respond to your enquiry. <a href="/privacy/#campaign-enquiries">How we handle enquiry data</a>.</p><p class="small">Please use public links and leave out passwords or payment details.</p>
<div class="enquiry-submit"><button class="button primary" type="submit" data-send-enquiry>Send campaign enquiry ${arrow}</button><span class="small">No account needed.</span></div><p id="enquiry-status" class="enquiry-status" role="status" aria-live="polite"></p>
<div class="enquiry-recovery" hidden><p>You can copy your answers and email them to <a href="mailto:contact@riseklix.com">contact@riseklix.com</a>, or <a href="${discord}">talk with us on Discord ${arrow}</a>.</p><button class="button outline" type="button" data-copy-enquiry>Copy my enquiry</button><label for="enquiry-copy" class="sr-only">Your enquiry to copy manually</label><textarea id="enquiry-copy" rows="8" readonly hidden></textarea></div><noscript><p class="small">You can submit this form without JavaScript. If email submission is unavailable, email <a href="mailto:contact@riseklix.com">contact@riseklix.com</a> or <a href="${discord}">join Discord</a>.</p></noscript></form></div>
<aside class="campaign-next"><p class="eyebrow">What happens next / 02</p><h2>From idea<br>to a clear plan.</h2><ol><li><strong>We review your enquiry.</strong><p>Your content, audience, and campaign goal give the conversation a starting point.</p></li><li><strong>We discuss the scope.</strong><p>Agree the source permissions, formats, platforms, review process, and budget.</p></li><li><strong>You decide the next step.</strong><p>Confirm availability and the written terms before any campaign begins.</p></li></ol><div class="campaign-email"><p>Prefer a direct conversation?</p><a href="mailto:contact@riseklix.com">contact@riseklix.com ${arrow}</a><a class="text-link" href="${discord}">Open RiseKlix Discord ${arrow}</a></div><p class="small">An enquiry does not reserve a campaign or create a payment commitment.</p></aside></section>
<section class="campaign-extras container"><details class="campaign-workbook"><summary><span><span class="eyebrow">Already have a plan? / 03</span><strong>Prepare a detailed campaign brief</strong><span>Optional. Create a draft to copy or download.</span></span><span aria-hidden="true">＋</span></summary>${briefTool()}</details><div id="talent-intro" class="campaign-clipper"><div><p class="eyebrow">For clippers and editors</p><h2>Want to make the cut?</h2><p>Start with the beginner guide and join the community to ask about current campaigns and requirements.</p></div><div class="tool-actions"><a class="button primary" href="/guides/how-to-become-a-clipper-india.html" data-clipper-entry data-discord-invite="${discord}">I want to clip ${arrow}</a><a class="button outline" href="${discord}">Open Discord ${arrow}</a></div></div></section>`;
