const examples=[
 {id:'podcast',name:'Podcast',number:'01',source:'One decision, explained.',line:'We changed one sentence in the onboarding flow. The product stayed the same. The confusion didn’t.',time:'06:24—07:08',hook:'The sentence that changed the experience.',moment:'Keep the decision and its explanation together. The interesting moment is the contrast, with enough context to understand it.',edit:'Start with the changed sentence, then reveal the reason. Add precise captions and preserve the speaker’s qualification.',destination:'Continue into the full conversation on the creator’s channel. Give the audience a specific next question to explore.',route:'/platforms/podcast-clipping-guide-india.html',link:'Read the podcast guide'},
 {id:'stream',name:'Live stream',number:'02',source:'The play. Then the payoff.',line:'Watch the route, not the scoreboard. That tiny detour is why the final move worked.',time:'18:10—18:47',hook:'The move before the winning move.',moment:'Find the setup that makes the payoff meaningful. A reaction alone can lose the story of how the moment happened.',edit:'Show the relevant route before the result. Keep the game readable in the crop and clear music or third-party material.',destination:'Point to the authorised stream and an identifiable creator account. Confirm what can be shared before publishing.',route:'/platforms/twitch-clips-permissions-campaign-guide.html',link:'Check stream permissions'},
 {id:'founder',name:'Founder story',number:'03',source:'Show the job, not the jargon.',line:'Here is the task we built for: taking a messy handoff and making the next action obvious.',time:'02:15—02:56',hook:'A clearer handoff, in one task.',moment:'Choose a concrete task instead of a broad product promise. The viewer should recognise the problem before seeing the solution.',edit:'Keep the before-and-after task connected. Remove private customer data and avoid implying unmeasured business results.',destination:'Use a relevant product explanation or campaign page that matches the clip’s promise. Make the next action clear.',route:'/blog/clipping-for-saas-founders-india.html',link:'Read the founder guide'}
];
const waves='<svg class="cut-wave" viewBox="0 0 420 72" fill="none" aria-hidden="true"><path d="M0 36h18m8-10v20m10-34v48m10-42v36m10-24v12m10-34v56m10-46v36m10-25v14m10-30v46m10-56v66m10-42v18m10-30v42m10-52v62m10-45v28m10-37v46m10-60v72m10-51v30m10-37v44m10-28v12m10-32v52m10-42v32m10-24v16m10-35v54m10-62v70m10-43v16m10-34v52m10-46v40m10-28v16m10-34v52m10-47v42m10-31v20m10-30v40m10-24v8m10-18v28m10-23v18m10-12v6m10-9v12m10-6h18" stroke="currentColor" stroke-width="2"/></svg>';
function cuttingDesk(arrow){return `<section class="cutting-desk" id="cutting-desk"><div class="container"><div class="desk-heading"><div><p class="eyebrow">Try an editing exercise</p><h2>Find the story.<br><em>Make the cut.</em></h2></div><p>Try three fictional examples. See how choosing the moment, making the edit and planning the next step work together.</p></div><div class="cut-switcher" role="group" aria-label="Choose a fictional editing example" hidden>${examples.map((x,i)=>`<button type="button" data-cut-select="${x.id}" aria-pressed="${i===0}" aria-controls="cut-${x.id}"><span aria-hidden="true">${x.number}</span>${x.name}</button>`).join('')}</div><div class="cut-panels">${examples.map(x=>`<article class="cut-example" id="cut-${x.id}" data-cut-panel="${x.id}" aria-label="${x.name} editing example"><div class="source-sheet"><div class="source-sheet-top"><span class="eyebrow">Fictional source note</span><span class="source-format">${x.name}</span></div><p class="source-title">${x.source}</p><blockquote>${x.line}</blockquote>${waves}<div class="source-time"><span>Illustrative timecodes</span><span>${x.time}</span></div><div class="cut-mark" aria-hidden="true">CUT <span>${x.number}</span> ↗</div></div><div class="edit-sheet"><p class="eyebrow">The short-form idea</p><h3>${x.hook}</h3><ol class="edit-decisions">${[['The moment',x.moment],['The edit',x.edit],['The next step',x.destination]].map(([label,copy],i)=>`<li><span aria-hidden="true">0${i+1}</span><div><h4>${label}</h4><p>${copy}</p></div></li>`).join('')}</ol><a class="text-link" href="${x.route}">${x.link} ${arrow}</a></div></article>`).join('')}</div><p class="desk-note">Demonstration only. Invented source lines and timecodes, with no campaign results implied.</p><p class="sr-only" id="cut-status" role="status"></p></div></section>`;}
function libraryTools(){return `<div class="library-tools" hidden><div class="library-views" role="group" aria-label="Resource layout"><button type="button" data-library-view="grid" aria-pressed="true">Cards</button><button type="button" data-library-view="list" aria-pressed="false">List</button></div><button type="button" id="saved-filter" aria-pressed="false">Saved <span id="saved-count">0</span></button><p class="library-note">Saved articles stay in this browser.</p></div><p class="sr-only" id="library-status" role="status"></p>`;}
function saveControl(slug,title){return `<button class="save-resource" type="button" data-save-resource="${slug}" aria-pressed="false" aria-label="Save: ${title}" hidden><span aria-hidden="true">＋</span><span data-save-label>Save</span></button>`;}
function readerTools(slug,title){return `<div class="reader-tools" hidden>${saveControl(slug,title)}<button type="button" data-copy-link>Copy link <span aria-hidden="true">↗</span></button><p id="reader-status" role="status">Save this article in this browser for later.</p></div>`;}
module.exports={cuttingDesk,libraryTools,saveControl,readerTools};
