const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function storyNavigation(){
 const chapters=[['clipper-start','Start clipping','Join'],['cutting-desk','Editing examples','Studio'],['how-it-works','How it works','Process'],['field-notes','Resource library','Read']];
 return `<nav class="story-navigation" aria-label="Homepage chapters" data-story-navigation><div class="container story-navigation-inner"><span class="story-index" aria-hidden="true">On this page</span><ol>${chapters.map(([id,label,short],index)=>`<li><a href="#${id}" aria-label="${label}"><span class="story-number" aria-hidden="true">${String(index+1).padStart(2,'0')}</span><span class="story-wide-label">${label}</span><span class="story-short-label" aria-hidden="true">${short}</span></a></li>`).join('')}</ol><a href="#top" class="scroll-top" data-scroll-top aria-label="Back to top">Top <span aria-hidden="true">↑</span></a></div><span class="story-progress" aria-hidden="true"></span></nav>`;
}
function readingDock(article,sections){
 const entries=[['direct-answer','Quick answer'],...(article.tool?[[article.tool==='brief'?'brief-builder':'calculator',article.tool==='brief'?'Build your brief':'Use the calculator']]:[]),...sections.map(section=>[section.id,section.heading]),...(article.faq.length?[['questions','Questions']]:[]),['sources','Sources & evidence']];
 return `<div class="reading-dock" data-reading-dock role="navigation" aria-label="Article reading navigation"><span class="reading-dock-label">On this page</span><form class="reading-jump" data-reading-jump hidden><label class="sr-only" for="reading-section">Jump to an article section</label><select id="reading-section" name="section">${entries.map(([id,label])=>`<option value="${id}">${esc(label)}</option>`).join('')}</select><button type="submit" aria-label="Go to selected article section">Go <span aria-hidden="true">→</span></button></form><a class="reading-static-index" href="#on-this-page">Contents</a><span class="reading-position" data-reading-position hidden aria-label="Article scroll position" title="Position through the article; this does not measure whether you have read it">0%</span><a href="#top" class="scroll-top" data-scroll-top aria-label="Back to top">Top <span aria-hidden="true">↑</span></a><span class="reading-progress" aria-hidden="true"><span data-reading-progress></span></span></div>`;
}
module.exports={storyNavigation,readingDock};
