// Curated journeys use existing complete articles, with native disclosure controls.
const routes=[
 {id:'creator',label:'Creators & YouTubers',title:'Give your long content a second life.',tone:'blue',copy:'Find a useful moment, preserve the explanation and choose where the clip should lead. Start with the format, then write the brief.',reads:[
  ['guides','youtube-tutorial-clipping-shorts-india','Find the teachable moment','Turn a long lesson into a Short that still answers the question.'],
  ['compare','instagram-reels-vs-youtube-shorts-clipping-india','Choose the right stage','Compare format, audience and measurement before publishing.'],
  ['blog','creator-clipping-brief-template-india','Make the brief','Use the editable template to define sources, scope and review.']],action:['/contact/','Plan a creator campaign']},
 {id:'company',label:'Company owners & teams',title:'Make the next customer question clearer.',tone:'amber',copy:'Connect the clip to a real task, a relevant destination and a measurement plan. Choose useful explanations before chasing a view count.',reads:[
  ['guides','b2b-webinar-clipping-qualified-leads-india','Build a useful next step','Turn webinar answers into clips with a relevant enquiry path.'],
  ['blog','clipping-for-saas-founders-india','Explain the product task','Keep the problem, demonstration and next action connected.'],
  ['blog','creator-clipping-campaign-roi-calculator-india','Check the economics','Model your own costs and attributable revenue in the calculator.']],action:['/contact/','Discuss a company campaign']},
 {id:'clipper',label:'Clippers & editors',title:'Bring your craft. Understand the brief.',tone:'violet',copy:'Learn the workflow, check source permissions and agree the actual approval and payout terms. Then ask about current opportunities in the community.',reads:[
  ['guides','how-to-become-a-clipper-india','Start with the beginner guide','Prepare permission-based samples and a clear introduction.'],
  ['platforms','youtube-reused-content-rules-indian-clippers','Understand reuse and originality','Separate source permission from platform monetisation rules.'],
  ['guides','how-much-do-clippers-make-india','Read the payment conditions','Estimate from an agreed rate, eligible views, fees and caps.']],action:['https://discord.gg/skQk3xZcRa','Join Discord as a clipper']}
];
function storyRoutes({location='home',arrow='',joinLink,articles}){
 for(const route of routes)for(const[section,slug]of route.reads)if(!articles.some(a=>a.section===section&&a.slug===slug))throw Error('Missing curated resource: '+slug);
 const body=`<section class="story-routes ${location==='library'?'reading-paths':'container'}" id="choose-your-route" aria-labelledby="route-heading"><div class="route-intro"><p class="eyebrow">Three ways forward</p><h2 id="route-heading">Find your<br><em>next good move.</em></h2><p>Choose what you’re here to do. Follow a short reading route, then put the plan to work.</p><div class="route-map" aria-hidden="true"><span>STORY</span><i></i><span>EDIT</span><i></i><span>NEXT MOVE ↗</span></div><a class="text-link" href="${location==='home'?'/resources/':'#resource-search'}">${location==='home'?'Browse every resource':'Explore the full library below'} ${arrow}</a></div><div class="route-choices">${routes.map((r,i)=>`<details class="story-route route-${r.tone}" name="${location}-story-route" ${i===0?'open':''}><summary><span class="route-index" aria-hidden="true">0${i+1}</span><span><span class="route-label">${r.label}</span><strong>${r.title}</strong></span><span class="route-toggle" aria-hidden="true">＋</span></summary><div class="route-body"><p>${r.copy}</p><ol>${r.reads.map(([section,slug,title,copy],n)=>`<li><a href="/${section}/${slug}.html"><span class="route-read-number" aria-hidden="true">0${n+1}</span><span><strong>${title}</strong><small>${copy}</small></span>${arrow}</a></li>`).join('')}</ol>${r.id==='clipper'?joinLink(r.action[1]):`<a class="button outline" href="${r.action[0]}">${r.action[1]} ${arrow}</a>`}</div></details>`).join('')}</div></section>`;
 return location==='library'?`<details class="library-route-disclosure"><summary><span><strong>Need a starting point?</strong><small>Explore reading routes for creators, company owners and clippers.</small></span><span aria-hidden="true">＋</span></summary>${body}</details>`:body;
}
module.exports={storyRoutes,routes};
