// Curated journeys use existing complete articles, with native disclosure controls.
const routes=[
 {id:'creator',label:'Creators & YouTubers',title:'Turn your videos into useful clips.',tone:'blue',copy:'Choose a moment viewers can understand on its own. Keep the explanation accurate, decide where to publish and write the campaign brief.',reads:[
  ['guides','youtube-tutorial-clipping-shorts-india','Find the teachable moment','Turn a long lesson into a Short that still answers the question.'],
  ['compare','instagram-reels-vs-youtube-shorts-clipping-india','Choose where to publish','Compare format, audience and measurement before publishing.'],
  ['blog','creator-clipping-brief-template-india','Write the brief','Use the editable template to define sources, scope and review.']],action:['/contact/','Plan a creator campaign']},
 {id:'company',label:'Company owners & teams',title:'Answer the questions your customers ask.',tone:'amber',copy:'Show a useful product task or answer a customer question. Send viewers to a relevant page and decide how you will measure visits or enquiries.',reads:[
  ['guides','b2b-webinar-clipping-qualified-leads-india','Build a useful next step','Turn webinar answers into clips with a relevant enquiry path.'],
  ['blog','clipping-for-saas-founders-india','Explain the product task','Keep the problem, demonstration and next action connected.'],
  ['blog','creator-clipping-campaign-roi-calculator-india','Estimate costs and return','Use your own costs and supported revenue figures in the calculator.']],action:['/contact/','Discuss a company campaign']},
 {id:'clipper',label:'Clippers & editors',title:'Learn the work. Check the terms.',tone:'violet',copy:'Learn the editing process and make samples with permission. Ask about current campaigns, then confirm the brief, review process and payment rules before working.',reads:[
  ['guides','how-to-become-a-clipper-india','Start with the beginner guide','Prepare samples using content you have permission to use.'],
  ['platforms','youtube-reused-content-rules-indian-clippers','Understand reuse and originality','Separate source permission from platform monetisation rules.'],
  ['guides','how-much-do-clippers-make-india','Read the payment conditions','Estimate from an agreed rate, eligible views, fees and caps.']],action:['https://discord.gg/skQk3xZcRa','Join Discord as a clipper']}
];
function storyRoutes({location='home',arrow='',joinLink,articles}){
 for(const route of routes)for(const[section,slug]of route.reads)if(!articles.some(a=>a.section===section&&a.slug===slug))throw Error('Missing curated resource: '+slug);
 const body=`<section class="story-routes ${location==='library'?'reading-paths':'container'}" id="choose-your-route" aria-labelledby="route-heading"><div class="route-intro"><p class="eyebrow">Where would you like to start?</p><h2 id="route-heading">Find the help<br><em>you need.</em></h2><p>Choose what you want to do. Start with three relevant guides and a clear next step.</p><div class="route-map" aria-hidden="true"><span>STORY</span><i></i><span>EDIT</span><i></i><span>NEXT MOVE ↗</span></div><a class="text-link" href="${location==='home'?'/resources/':'#resource-search'}">${location==='home'?'Browse every resource':'Browse the full library below'} ${arrow}</a></div><div class="route-choices">${routes.map((r,i)=>`<details class="story-route route-${r.tone}" name="${location}-story-route" ${i===0?'open':''}><summary><span class="route-index" aria-hidden="true">0${i+1}</span><span><span class="route-label">${r.label}</span><strong>${r.title}</strong></span><span class="route-toggle" aria-hidden="true">＋</span></summary><div class="route-body"><p>${r.copy}</p><ol>${r.reads.map(([section,slug,title,copy],n)=>`<li><a href="/${section}/${slug}.html"><span class="route-read-number" aria-hidden="true">0${n+1}</span><span><strong>${title}</strong><small>${copy}</small></span>${arrow}</a></li>`).join('')}</ol>${r.id==='clipper'?joinLink(r.action[1]):`<a class="button outline" href="${r.action[0]}">${r.action[1]} ${arrow}</a>`}</div></details>`).join('')}</div></section>`;
 return location==='library'?`<details class="library-route-disclosure"><summary><span><strong>Need a starting point?</strong><small>Start with guides for creators, company owners or clippers.</small></span><span aria-hidden="true">＋</span></summary>${body}</details>`:body;
}
module.exports={storyRoutes,routes};
